---
Resources:
#Private route table 
  BastionEUPrivateRTB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: BstEuVPC
      Tags:
      - Key: stack
        Value: production
      - Key: Name
        Value: fh-bst-eu-private-rtb

  ProductionEUPrivateRTB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: ProdEuVPC
      Tags:
      - Key: stack
        Value: production
      - Key: Name
        Value: fh-prod-eu-private-rtb

#Public route table

  BastionEUPublicRTB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: BstEuVPC
      Tags:
      - Key: stack
        Value: production
      - Key: Name
        Value: fh-bst-eu-public-rtb

  ProductionEUPublicRTB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: ProdEuVPC
      Tags:
      - Key: stack
        Value: production
      - Key: Name
        Value: fh-prod-eu-public-rtb


#association route table with subnet

######
# bst
#####

  BastionEUPrivateRTBPrivateSubnet1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: 
    - BastionEUPrivateRTB
    - BastionPrivateSubnet1a
    Properties:
      RouteTableId: !Ref BastionEUPrivateRTB
      SubnetId: !Ref BastionPrivateSubnet1a

  BastionEUPrivateRTBPrivateSubnet1b:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: 
    - BastionEUPrivateRTB
    - BastionPrivateSubnet1b
    Properties:
      RouteTableId: !Ref BastionEUPrivateRTB
      SubnetId: !Ref BastionPrivateSubnet1b

  BastionEUPublicRTBPublicSubnet1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: 
    - BastionEUPublicRTB
    - BastionPublicSubnet1a
    Properties:
      RouteTableId: !Ref BastionEUPublicRTB
      SubnetId: !Ref BastionPublicSubnet1a   

  BastionEUPublicRTBPublicSubnet1b:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: 
    - BastionEUPublicRTB
    - BastionPublicSubnet1b
    Properties:
      RouteTableId: !Ref BastionEUPublicRTB
      SubnetId: !Ref BastionPublicSubnet1b   

######
# Production 
###

  ProdEUPrivateRTBPrivateSubnet1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: 
    - ProductionEUPrivateRTB
    - ProductionPrivateSubnet1a
    Properties:
      RouteTableId: !Ref ProductionEUPrivateRTB
      SubnetId: !Ref ProductionPrivateSubnet1a

  ProdEUPrivateRTBPrivateSubnet1b:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: 
    - ProductionEUPrivateRTB
    - ProductionPrivateSubnet1b    
    Properties:
      RouteTableId: !Ref ProductionEUPrivateRTB
      SubnetId: !Ref ProductionPrivateSubnet1b

  ProdEUPublicRTBPublicSubnet1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: 
    - ProductionEUPublicRTB
    - ProductionPublicSubnet1a   
    Properties:
      RouteTableId: !Ref ProductionEUPublicRTB
      SubnetId: !Ref ProductionPublicSubnet1a

  ProdEUPublicRTBPublicSubnet1b:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: 
    - ProductionEUPublicRTB
    - ProductionPublicSubnet1b   
    Properties:
      RouteTableId: !Ref ProductionEUPublicRTB
      SubnetId: !Ref ProductionPublicSubnet1b
