---
Resources:


##
# Internet Gateway
##

  InternetGateway:
    Type: AWS::EC2::InternetGateway
  
  InternetGatewayAttachmentBastion:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      VpcId: !Ref BstEuVPC
      InternetGatewayId: !Ref InternetGateway  

  InternetGatewayAttachmentProduction:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      VpcId: !Ref ProdEuVPC
      InternetGatewayId: !Ref InternetGateway

######
# VPCs
#####

  BstEuVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsSupport: 'True'
      EnableDnsHostnames: 'True'
      Tags:
        - Key: Name
          Value: fh-eu-bst
    DeletionPolicy: Delete

    

  ProdEuVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.2.0.0/16
      EnableDnsSupport: 'True'
      EnableDnsHostnames: 'True'
      Tags:
        - Key: Name
          Value: fh-eu-prod
    DeletionPolicy: Delete

########
# private and public subnets
########

  BastionPrivateSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BstEuVPC
      CidrBlock: 10.1.1.0/24
      AvailabilityZone: "eu-west-1a"
      Tags:
      - Key: stack
        Value: bastian
      - Key: Name
        Value: fh-bst-private1-subnet-eu-west-1a


  BastionPrivateSubnet1b:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BstEuVPC
      CidrBlock: 10.1.2.0/24
      AvailabilityZone: "eu-west-1b"
      Tags:
      - Key: stack
        Value: bastian
      - Key: Name
        Value: fh-bst-private2-subnet-eu-west-1b


  BastionPublicSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BstEuVPC
      CidrBlock: 10.1.3.0/24
      AvailabilityZone: "eu-west-1a"
      Tags:
       - Key: stack
         Value: bastian
       - Key: Name
         Value: fh-bst-public1-subnet-eu-west-1a

  BastionPublicSubnet1b:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BstEuVPC
      CidrBlock: 10.1.4.0/24
      AvailabilityZone: "eu-west-1b"
      Tags:
      - Key: stack
        Value: bastian
      - Key: Name
        Value: fh-bst-public2-subnet-eu-west-1b

######
# Production Subnet
###
  ProductionPrivateSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ProdEuVPC
      CidrBlock: 10.2.1.0/24
      AvailabilityZone: "eu-west-1a"
      Tags:
      - Key: stack
        Value: Production
      - Key: Name
        Value: fh-prod-private1-subnet-eu-west-1a

  ProductionPrivateSubnet1b:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ProdEuVPC
      CidrBlock: 10.2.2.0/24
      AvailabilityZone: "eu-west-1b"
      Tags:
      - Key: stack
        Value: Production
      - Key: Name
        Value: fh-prod-private2-subnet-eu-west-1b


  ProductionPublicSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ProdEuVPC
      CidrBlock: 10.2.3.0/24
      AvailabilityZone: "eu-west-1a"
      Tags:
      - Key: stack
        Value: Production
      - Key: Name
        Value: fh-prod-public1-subnet-eu-west-1a

  ProductionPublicSubnet1b:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ProdEuVPC
      CidrBlock: 10.2.4.0/24
      AvailabilityZone: "eu-west-1b"
      Tags:
      - Key: stack
        Value: Production
      - Key: Name
        Value: fh-prod-public2-subnet-eu-west-1b

##
# Nat Gateway
##
